language: java
# Enable container-based infrastructure
# see https://docs.travis-ci.com/user/reference/overview/
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk7

notifications:
  email: false

script:
- ./mvnw clean verify
